"""remove string length limit from column password_hash in user model

Revision ID: 23c828e08362
Revises: aeb1dae3b26c
Create Date: 2022-03-04 11:34:57.998906

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "23c828e08362"
down_revision = "aeb1dae3b26c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products",
        "price",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=2),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products",
        "price",
        existing_type=sa.Float(precision=2),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
