"""create column confirmed_email in UserModel

Revision ID: a36a4a488e84
Revises: 23c828e08362
Create Date: 2022-03-09 14:05:58.865989

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a36a4a488e84"
down_revision = "23c828e08362"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "products",
        "price",
        existing_type=sa.REAL(),
        type_=sa.Float(precision=2),
        existing_nullable=False,
    )
    op.add_column("users", sa.Column("confirmed_email", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "confirmed_email")
    op.alter_column(
        "products",
        "price",
        existing_type=sa.Float(precision=2),
        type_=sa.REAL(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
